const rawAmount = { type: "string", pattern: "^(0|[1-9][0-9]*)$" };
const nullableDate = { type: ["string", "null"], format: "date-time" };
const evidenceRef = {
  type: "object",
  required: ["account", "lt", "hash", "utime"],
  properties: {
    account: { type: "string" },
    lt: rawAmount,
    hash: { type: "string" },
    utime: { type: "integer" },
  },
};
const signedRaw = { type: "string", pattern: "^-?(0|[1-9][0-9]*)$" };
const perpsSnapshot = {
  type: "object",
  required: ["account", "position", "pending"],
  properties: {
    account: {
      type: "object",
      required: [
        "collateralRaw",
        "pendingFundingRaw",
        "crossMargin",
        "referralLinked",
        "openPositionCount",
      ],
      properties: {
        collateralRaw: rawAmount,
        pendingFundingRaw: signedRaw,
        crossMargin: { type: "integer" },
        referralLinked: { type: "integer" },
        openPositionCount: { type: "integer" },
      },
    },
    position: {
      type: ["object", "null"],
      properties: {
        owner: { type: "string" },
        marketId: { type: "integer" },
        sizeRaw: signedRaw,
        marginRaw: rawAmount,
        entryNotionalRaw: rawAmount,
        lastFundingIndexRaw: signedRaw,
        flags: { type: "integer" },
      },
    },
    pending: {
      type: ["object", "null"],
      properties: {
        kind: { type: "integer" },
        owner: { type: ["string", "null"] },
        marketId: { type: "integer" },
        wireId: rawAmount,
        amountRaw: rawAmount,
        queuedRaw: rawAmount,
        recordedAt: signedRaw,
      },
    },
  },
};
const hash256 = { type: "string", pattern: "^[0-9a-f]{64}$" };
const nullableHash256 = { ...hash256, type: ["string", "null"] };
const optionSeriesCapacity = {
  type: "object", additionalProperties: false,
  required: ["kind", "optionAddress", "openNotionalRaw", "collateralLockedRaw"],
  properties: {
    kind: { type: "integer", enum: [1, 2] }, optionAddress: { type: "string" },
    openNotionalRaw: rawAmount, collateralLockedRaw: rawAmount,
  },
};
const optionAbortTrigger = {
  oneOf: [
    { type: "object", additionalProperties: false, required: ["kind", "bodyHash"],
      properties: { kind: { const: "owner_abort" }, bodyHash: hash256 } },
    { type: "object", additionalProperties: false,
      required: ["kind", "bodyHash", "bodyBoc", "opcode", "wireId", "originalMessageBodyHash", "failedTransaction", "recoveryTransaction", "factoryUnwind"],
      properties: {
        kind: { const: "initial_series_buy_bounced" }, bodyHash: hash256,
        bodyBoc: { type: "string", description: "Actual standard VM bounce: marker 0xffffffff and exactly the first 256 bits of the original assigned BOYR/BBUY body, with no refs." },
        opcode: { type: "integer", enum: [0x424f5952, 0x42425559] }, wireId: rawAmount,
        originalMessageBodyHash: hash256, failedTransaction: evidenceRef, recoveryTransaction: evidenceRef,
        factoryUnwind: { type: "object", additionalProperties: false,
          required: ["seriesBuyIndexBefore", "seriesBuyIndexAfter", "beforeSeries", "afterSeries"],
          properties: { seriesBuyIndexBefore: rawAmount, seriesBuyIndexAfter: { type: "null" },
            beforeSeries: optionSeriesCapacity, afterSeries: optionSeriesCapacity } },
      } },
  ],
};
const optionVaultBucket = {
  type: ["object", "null"],
  required: [
    "lockedRaw", "premiumRaw", "reservedLockedRaw", "reservedPremiumRaw",
    "liabilityActionId", "liabilityStatus", "liabilityLastDispatchTs",
    "liabilityRequestHash", "liabilityTargetNotionalRaw", "liabilityTargetImRaw",
    "liabilityTargetCmRaw",
  ],
  properties: {
    lockedRaw: rawAmount,
    premiumRaw: rawAmount,
    reservedLockedRaw: rawAmount,
    reservedPremiumRaw: rawAmount,
    liabilityActionId: rawAmount,
    liabilityStatus: { type: "integer", minimum: 0, maximum: 255 },
    liabilityLastDispatchTs: signedRaw,
    liabilityRequestHash: hash256,
    liabilityTargetNotionalRaw: rawAmount,
    liabilityTargetImRaw: rawAmount,
    liabilityTargetCmRaw: rawAmount,
  },
};
const t3RecoveryWallet = {
  type: "object",
  required: ["balanceRaw", "owner", "root", "journal", "dataHash"],
  properties: {
    balanceRaw: rawAmount,
    owner: { type: "string" },
    root: { type: "string" },
    dataHash: hash256,
    journal: {
      type: "object",
      required: ["status", "queryId", "amountRaw", "requestHash", "response"],
      properties: {
        status: { type: "integer", minimum: 0, maximum: 5 },
        queryId: rawAmount,
        amountRaw: rawAmount,
        requestHash: hash256,
        response: { type: ["string", "null"] },
      },
    },
  },
};
const t3RecoveryRoot = {
  type: "object",
  required: [
    "enabled",
    "withdrawalsOnly",
    "totalSupplyRaw",
    "emitter",
    "walletCodeHash",
    "receiptHash",
    "pendingHash",
    "negativeHash",
    "acceptedHash",
    "wireWalletHash",
    "wireQueryId",
    "wireIntentHash",
    "wireAmountRaw",
    "dataHash",
  ],
  properties: {
    enabled: { type: "integer", enum: [0, 1] },
    withdrawalsOnly: { type: "integer", enum: [0, 1] },
    totalSupplyRaw: rawAmount,
    emitter: { type: ["string", "null"] },
    walletCodeHash: hash256,
    receiptHash: nullableHash256,
    pendingHash: nullableHash256,
    negativeHash: nullableHash256,
    acceptedHash: nullableHash256,
    wireWalletHash: nullableHash256,
    wireQueryId: { ...rawAmount, type: ["string", "null"] },
    wireIntentHash: nullableHash256,
    wireAmountRaw: { ...rawAmount, type: ["string", "null"] },
    dataHash: hash256,
  },
};
const t3RecoveryHub = {
  type: "object",
  required: ["root", "enabled", "proof", "dataHash"],
  properties: {
    root: { type: "string" },
    enabled: { type: "integer", enum: [0, 1] },
    dataHash: hash256,
    proof: {
      type: ["object", "null"],
      required: [
        "queryId",
        "wireId",
        "owner",
        "recipient",
        "amountRaw",
        "slippage",
        "mode",
        "outputToken",
        "payoutId",
        "consumed",
      ],
      properties: {
        queryId: rawAmount,
        wireId: rawAmount,
        owner: { type: "string" },
        recipient: { type: "string" },
        amountRaw: rawAmount,
        slippage: { type: "integer" },
        mode: { type: "integer" },
        outputToken: { type: "integer" },
        payoutId: rawAmount,
        consumed: { type: "integer", enum: [0, 1] },
      },
    },
  },
};
const t3RecoveryBoundary = (state: object) => ({
  type: "object",
  required: ["before", "after", "evidence"],
  properties: {
    before: state,
    after: state,
    evidence: {
      type: "object",
      required: [
        "kind",
        "stateBeforeHash",
        "stateAfterHash",
        "beforeSeqno",
        "afterSeqno",
        "transactions",
      ],
      properties: {
        kind: { type: "string", enum: ["t3_burn"] },
        stateBeforeHash: hash256,
        stateAfterHash: hash256,
        beforeSeqno: { type: "integer" },
        afterSeqno: { type: "integer" },
        transactions: { type: "array", items: evidenceRef },
      },
    },
  },
});
export const ledgerSchemas = {
  LedgerT3BurnRecovery: {
    type: "object",
    description:
      "Historical proof that a later owner REDM recovered the original T3 burn acknowledgement without another burn. Acceptance does not certify receiver payout or wallet journal cleanup.",
    required: [
      "status",
      "binding",
      "continuationRequestBodyHash",
      "originalWallet",
      "originalRoot",
      "originalProof",
      "continuation",
      "rootAcceptance",
      "walletAcceptance",
      "evidence",
    ],
    properties: {
      status: { type: "string", enum: ["accepted"] },
      binding: {
        type: "object",
        additionalProperties: false,
        required: [
          "network",
          "hub",
          "root",
          "hubCodeHash",
          "rootCodeHash",
          "walletCodeHash",
          "receiverCodeHash",
          "reserveRoutes",
        ],
        properties: {
          network: { type: "string", enum: ["localnet", "testnet", "mainnet"] },
          hub: { type: "string" },
          root: { type: "string" },
          hubCodeHash: hash256,
          rootCodeHash: hash256,
          walletCodeHash: hash256,
          receiverCodeHash: hash256,
          reserveRoutes: {
            type: "array",
            minItems: 3,
            maxItems: 3,
            items: {
              type: "object",
              additionalProperties: false,
              required: ["root", "vault", "discovery"],
              properties: {
                root: { type: "string" },
                vault: { type: "string" },
                discovery: { type: "string" },
              },
            },
          },
        },
      },
      continuationRequestBodyHash: hash256,
      originalWallet: t3RecoveryBoundary(t3RecoveryWallet),
      originalRoot: t3RecoveryBoundary(t3RecoveryRoot),
      originalProof: t3RecoveryBoundary(t3RecoveryHub),
      continuation: t3RecoveryBoundary(t3RecoveryHub),
      rootAcceptance: t3RecoveryBoundary(t3RecoveryRoot),
      walletAcceptance: t3RecoveryBoundary(t3RecoveryWallet),
      evidence: { type: "array", items: evidenceRef },
    },
  },
  LedgerAsset: {
    type: "object",
    required: ["kind", "id"],
    properties: {
      kind: {
        type: "string",
        enum: [
          "native",
          "jetton",
          "lp_position",
          "option_position",
          "perps_balance",
          "unknown",
        ],
      },
      id: { type: "string" },
      master: { type: "string" },
      wallet: { type: "string" },
      owner: { type: "string" },
      controller: { type: "string" },
      engine: { type: "string" },
      balanceType: {
        type: "string",
        enum: ["collateral", "funding", "payout"],
      },
      custody: { type: "string", enum: ["t3_receiver"] },
      symbol: { type: "string" },
      decimals: { type: "integer", minimum: 0, maximum: 255 },
      pool: { type: "string" },
      binId: { type: "integer" },
      factory: { type: "string" },
      series: { type: "string" },
      seriesId: rawAmount,
      positionId: rawAmount,
    },
  },
  LedgerMovement: {
    type: "object",
    required: ["id", "direction", "asset", "amountRaw", "evidence"],
    properties: {
      id: { type: "string" },
      direction: { type: "string", enum: ["in", "out", "fee"] },
      purpose: {
        type: "string",
        enum: [
          "option_premium",
          "option_collateral",
          "protocol_fee",
          "option_excess",
          "option_payout",
          "option_refund",
          "option_right_retired",
          "t3_collateral",
          "t3_mint",
          "t3_burn",
          "t3_payout",
          "perps_collateral",
          "perps_funding",
          "perps_payout",
        ],
      },
      asset: { $ref: "#/components/schemas/LedgerAsset" },
      amountRaw: rawAmount,
      source: { type: "string" },
      destination: { type: "string" },
      evidence: {
        type: "object",
        required: ["kind"],
        properties: {
          kind: {
            type: "string",
            enum: [
              "native_message",
              "transaction_fee",
              "message_forward_fee",
              "jetton_notification",
              "jetton_internal_transfer",
              "jetton_transfer",
              "lp_position_delta",
              "option_activation",
              "option_position_delta",
              "option_payout",
              "option_refund",
              "sccp_burn_record",
              "sccp_mint",
              "t3_mint",
              "t3_burn",
              "t3_payout",
              "perps_account_delta",
              "perps_payout",
            ],
          },
          messageIndex: { type: "integer" },
          opcode: { type: "integer" },
          bodyHash: { type: "string" },
          requestBodyHash: { type: "string", pattern: "^[0-9a-f]{64}$" },
          queryId: { type: "string", pattern: "^(0|[1-9][0-9]*)$" },
          transactions: { type: "array", items: evidenceRef },
          stateBeforeHash: { type: "string" },
          stateAfterHash: { type: "string" },
          beforeSeqno: { type: "integer" },
          afterSeqno: { type: "integer" },
          optionPosition: {
            type: "object",
            required: [
              "factory",
              "factoryCodeHash",
              "seriesId",
              "positionId",
              "owner",
              "sourceWallet",
              "notionalRaw",
              "premiumRaw",
              "collateralRaw",
              "seriesWireId",
              "custodyWireId",
              "protocolFeeRaw",
              "excessRaw",
              "beforeBuyStateRaw",
              "buyStateRaw",
            ],
            properties: {
              factory: { type: "string" },
              factoryCodeHash: { type: "string", pattern: "^[0-9a-f]{64}$" },
              seriesId: rawAmount,
              positionId: rawAmount,
              owner: { type: "string" },
              sourceWallet: { type: "string" },
              notionalRaw: rawAmount,
              premiumRaw: rawAmount,
              collateralRaw: rawAmount,
              seriesWireId: rawAmount,
              custodyWireId: rawAmount,
              protocolFeeRaw: rawAmount,
              excessRaw: rawAmount,
              beforeBuyStateRaw: rawAmount,
              buyStateRaw: rawAmount,
            },
            description:
              "Original owner/amount/wire identity from exact historical factory state at the first activation ACK. Outer evidence binds both data hashes, code hash, block boundaries and causal transactions. A current mutable position getter is not historical proof.",
          },
          getter: {
            type: "object",
            required: ["account", "method", "args", "result", "observedAt"],
            properties: {
              account: { type: "string" },
              method: {
                type: "string",
                enum: ["get_sccp_burn_record", "redemption_identity"],
              },
              args: { type: "array", items: { type: "string" } },
              result: { type: "array", items: { type: "string" } },
              observedAt: { type: "string", format: "date-time" },
            },
            description:
              "Authenticated current getter observation. get_sccp_burn_record returns a record BOC in result[0] keyed by the decimal message ID argument. Neither is historical valuation or cross-chain finality.",
          },
        },
      },
    },
  },
  LedgerEvent: {
    type: "object",
    required: [
      "id",
      "network",
      "account",
      "lt",
      "hash",
      "txId",
      "utime",
      "status",
      "kind",
      "totalFeesRaw",
      "movements",
      "actions",
      "issues",
    ],
    properties: {
      id: { type: "string" },
      network: { type: "string", enum: ["mainnet", "testnet", "localnet"] },
      account: { type: "string" },
      lt: rawAmount,
      hash: { type: "string" },
      txId: { type: "string" },
      utime: { type: "integer" },
      status: { type: "string", enum: ["success", "failed", "pending"] },
      kind: { type: "string" },
      totalFeesRaw: {
        type: ["string", "null"],
        description:
          "Sum of native transaction fees across grouped owned accounts, also represented by transaction_fee movements. Never sum both. Outgoing message forwarding/IHR fees are separate fee movements.",
      },
      movements: {
        type: "array",
        items: { $ref: "#/components/schemas/LedgerMovement" },
      },
      actions: {
        type: "array",
        items: { type: "object" },
        description:
          "Classifier hints; these do not certify downstream settlement.",
      },
      issues: { type: "array", items: { type: "string" } },
      settlement: {
        type: "object",
        required: ["status", "protocol", "operation", "evidence"],
        properties: {
          status: { type: "string", enum: ["confirmed", "incomplete"] },
          protocol: {
            type: "string",
            enum: ["dlmm", "jetton", "options", "sccp", "t3", "perps"],
          },
          operation: {
            type: "string",
            enum: [
              "swap",
              "lp_deposit",
              "lp_withdraw",
              "transfer",
              "option_buy",
              "option_exercise",
              "option_refund",
              "bridge_burn",
              "bridge_mint",
              "t3_mint",
              "t3_redeem",
              "perps_operation",
            ],
          },
          optionLifecycle: {
            type: "object",
            required: [
              "factory",
              "factoryCodeHash",
              "root",
              "owner",
              "recipient",
              "outcome",
              "payout",
              "protocolAccounting",
              "localNetworkFees",
            ],
            description:
              "Historical qualified option lifecycle. A confirmed exercise retires the original holder right; payout completion is separate. Liability/premium release is accounting only, never another cash movement. Lifecycle exercise bodies have no user query ID. Refund completion is one ingress/excess claim, not a complete aborted-position unwind.",
            properties: {
              factory: { type: "string" },
              factoryCodeHash: { type: "string", pattern: "^[0-9a-f]{64}$" },
              vault: { type: "string" },
              vaultCodeHash: { type: "string", pattern: "^[0-9a-f]{64}$" },
              root: { type: "string" },
              series: { type: "string" },
              productCodeHash: { type: "string", pattern: "^[0-9a-f]{64}$" },
              optionKind: { type: "integer", enum: [1, 2] },
              seriesId: rawAmount,
              positionId: rawAmount,
              owner: { type: "string" },
              recipient: { type: "string" },
              originalRequestBodyHash: {
                type: "string",
                pattern: "^[0-9a-f]{64}$",
              },
              requestedPayoutRaw: rawAmount,
              requestedPremiumBurnRaw: rawAmount,
              outcome: {
                type: "string",
                enum: ["exercised", "refunded", "pending"],
              },
              beforePosition: {
                type: ["object", "null"],
                additionalProperties: true,
                description:
                  "Original factory position, exact atomic strings and dataHash.",
              },
              afterPosition: {
                type: ["object", "null"],
                additionalProperties: true,
                description:
                  "Terminal factory position; no latest getter substitution.",
              },
              productBefore: { type: "object", additionalProperties: true },
              productAfter: { type: "object", additionalProperties: true },
              requestEvidence: { type: "object", additionalProperties: true },
              productEvidence: { type: "object", additionalProperties: true },
              positionEvidence: { type: "object", additionalProperties: true },
              collateralLiabilityReleasedRaw: rawAmount,
              premiumAccountingReleasedRaw: rawAmount,
              payout: {
                type: "object",
                required: ["status", "amountRaw", "evidence"],
                properties: {
                  status: {
                    type: "string",
                    enum: ["none", "pending", "completed"],
                  },
                  amountRaw: {
                    type: ["string", "null"],
                    description:
                      "Null until the qualified product/factory position transition proves the actual amount. Caller requested payout is separate intent.",
                  },
                  issue: { type: "string" },
                  wireId: rawAmount,
                  sourceWallet: { type: "string" },
                  destinationWallet: { type: "string" },
                  requestHash: { type: "string", pattern: "^[0-9a-f]{64}$" },
                  journalKey: { type: "string", pattern: "^[0-9a-f]{64}$" },
                  beforeJournal: { type: "object", additionalProperties: true },
                  afterJournal: { type: "object", additionalProperties: true },
                  evidence: { type: "array", items: evidenceRef },
                },
              },
              protocolAccounting: {
                type: "object",
                required: ["status"],
                properties: {
                  status: {
                    type: "string",
                    enum: ["not_required", "unverified", "confirmed"],
                  },
                  riskClaimId: rawAmount,
                  riskRequestHash: { type: "string" },
                  riskDeliveredRaw: rawAmount,
                },
                description:
                  "A reported risk status/delivery amount is retained metadata. Risk reimbursement cash requires independent custody evidence and remains unverified in this decoder.",
              },
              refund: {
                type: "object",
                required: ["kind", "scope"],
                properties: {
                  kind: {
                    type: "string",
                    enum: ["ingress", "excess", "aborted_buy"],
                  },
                  scope: {
                    type: "string",
                    enum: ["individual_claim", "position_unwind"],
                  },
                  claimId: rawAmount,
                  identityHash: { type: "string" },
                  queryId: rawAmount,
                  payloadHash: { type: "string" },
                  beforeClaim: { type: "object", additionalProperties: true },
                  unwind: {
                    type: "object",
                    required: [
                      "funding",
                      "trigger",
                      "beforeAbortBuyStateRaw",
                      "reservationStatus",
                      "reservationEvidence",
                      "reservationStateEvidence",
                      "custody",
                      "cancellation",
                      "factoryReturn",
                      "vaultReturn",
                    ],
                    description:
                      "A required trigger identifies owner OBAR or a qualified failed initial BOYR/BBUY with its actual VM bounce and exact factory unwind. Original funding and historical allocation remain separate from cancellation and actual factory/vault cash returns. A completed aggregate payout means the independently proven returns sum to original funding; never add another cash movement from this metadata.",
                    properties: {
                      funding: {
                        type: "object",
                        required: [
                          "queryId",
                          "amountRaw",
                          "ownerWallet",
                          "factoryWallet",
                          "requestBodyHash",
                          "payloadHash",
                          "evidence",
                          "stateEvidence",
                        ],
                        properties: {
                          queryId: rawAmount,
                          amountRaw: rawAmount,
                          ownerWallet: { type: "string" },
                          factoryWallet: { type: "string" },
                          requestBodyHash: {
                            type: "string",
                            pattern: "^[0-9a-f]{64}$",
                          },
                          payloadHash: {
                            type: "string",
                            pattern: "^[0-9a-f]{64}$",
                          },
                          evidence: { type: "array", items: evidenceRef },
                          stateEvidence: {
                            type: "object",
                            additionalProperties: true,
                          },
                        },
                      },
                      trigger: optionAbortTrigger,
                      beforeAbortBuyStateRaw: rawAmount,
                      reservationStatus: {
                        type: "string",
                        enum: ["reserved", "failed"],
                      },
                      reservationEvidence: {
                        type: "array",
                        items: evidenceRef,
                      },
                      reservationStateEvidence: {
                        type: "object",
                        additionalProperties: true,
                      },
                      custody: { type: "object", additionalProperties: true },
                      commit: { type: "object", additionalProperties: true },
                      cancellation: {
                        type: "object",
                        additionalProperties: true,
                      },
                      vaultAbort: {
                        type: "object",
                        description: "Exact historical OBAB boundary. A null receiptBeforeHash proves no prior deposit receipt; omitted fields never prove orphan custody. Committed deposits release their bucket with unchanged tracked balance. Orphan custody adds the exact principal with unchanged buckets and aggregate locked/premium totals.",
                        required: [
                          "receiptHash", "abortHash", "receiptBeforeHash",
                          "receiptAfterHash", "trackedBalanceBeforeRaw",
                          "trackedBalanceAfterRaw", "requestHash", "journalKey",
                          "evidence", "stateEvidence", "beforeBucket", "afterBucket",
                        ],
                        properties: {
                          receiptHash: hash256,
                          abortHash: hash256,
                          receiptBeforeHash: nullableHash256,
                          receiptAfterHash: hash256,
                          trackedBalanceBeforeRaw: rawAmount,
                          trackedBalanceAfterRaw: rawAmount,
                          requestHash: hash256,
                          journalKey: hash256,
                          evidence: { type: "array", minItems: 1, maxItems: 1, items: evidenceRef },
                          stateEvidence: { type: "object", additionalProperties: true },
                          beforeBucket: optionVaultBucket,
                          afterBucket: optionVaultBucket,
                        },
                      },
                      factoryReturn: {
                        type: "object",
                        additionalProperties: true,
                      },
                      vaultReturn: {
                        type: "object",
                        additionalProperties: true,
                      },
                    },
                  },
                },
              },
              localNetworkFees: {
                type: "array",
                items: {
                  type: "object",
                  required: [
                    "transaction",
                    "amountRaw",
                    "includedInOwnerFeeMovements",
                  ],
                  properties: {
                    transaction: evidenceRef,
                    amountRaw: { type: ["string", "null"] },
                    includedInOwnerFeeMovements: { type: "boolean" },
                  },
                },
              },
            },
          },
          perps: {
            type: "object",
            required: [
              "engine",
              "engineCodeHash",
              "root",
              "owner",
              "ownerWallet",
              "engineWallet",
              "marketId",
              "positionKey",
              "queryId",
              "request",
              "outcome",
              "depositRaw",
              "payout",
              "localNetworkFees",
            ],
            properties: {
              engine: { type: "string" },
              engineCodeHash: { type: "string", pattern: "^[0-9a-f]{64}$" },
              root: { type: "string" },
              owner: { type: "string" },
              ownerWallet: { type: "string" },
              engineWallet: { type: "string" },
              marketId: { type: "integer", minimum: 0 },
              positionKey: { type: "string", pattern: "^[0-9a-f]{64}$" },
              queryId: rawAmount,
              fundingQueryId: rawAmount,
              depositRaw: rawAmount,
              outcome: {
                type: "string",
                enum: ["accepted", "rejected", "retry", "unresolved"],
              },
              request: {
                type: "object",
                required: ["opcode", "operation", "queryId", "marketId"],
                properties: {
                  opcode: { type: "integer" },
                  operation: {
                    type: "string",
                    enum: [
                      "open",
                      "modify",
                      "close",
                      "add_margin",
                      "remove_margin",
                      "claim",
                      "liquidation",
                      "adl",
                    ],
                  },
                  queryId: rawAmount,
                  marketId: { type: "integer" },
                  owner: { type: "string" },
                  sizeRaw: { type: "string" },
                  marginRaw: { type: "string" },
                  limitPriceRaw: rawAmount,
                  leverageBps: { type: "integer" },
                  flags: { type: "integer" },
                  referrer: { type: ["string", "null"] },
                },
              },
              before: perpsSnapshot,
              after: perpsSnapshot,
              economics: {
                type: "object",
                required: [
                  "outcome",
                  "fundingRaw",
                  "realizedPnlRaw",
                  "tradeFeeRaw",
                  "depositCollateralRaw",
                  "excessRaw",
                  "payoutContributionRaw",
                  "adlAbsorbedRaw",
                  "badDebtRaw",
                  "tradedNotionalRaw",
                  "executedSizeRaw",
                ],
                properties: {
                  outcome: {
                    type: "string",
                    enum: ["accepted", "rejected", "retry"],
                  },
                  fundingRaw: signedRaw,
                  realizedPnlRaw: signedRaw,
                  tradeFeeRaw: rawAmount,
                  depositCollateralRaw: rawAmount,
                  excessRaw: rawAmount,
                  payoutContributionRaw: rawAmount,
                  adlAbsorbedRaw: rawAmount,
                  badDebtRaw: rawAmount,
                  tradedNotionalRaw: rawAmount,
                  executedSizeRaw: signedRaw,
                },
              },
              stateEvidence: {
                type: "object",
                required: [
                  "kind",
                  "stateBeforeHash",
                  "stateAfterHash",
                  "beforeSeqno",
                  "afterSeqno",
                  "transactions",
                ],
                properties: {
                  kind: { type: "string", enum: ["perps_account_delta"] },
                  stateBeforeHash: { type: "string" },
                  stateAfterHash: { type: "string" },
                  beforeSeqno: { type: "integer" },
                  afterSeqno: { type: "integer" },
                  transactions: { type: "array", items: evidenceRef },
                },
              },
              payout: {
                type: "object",
                required: ["status", "amountRaw", "evidence"],
                properties: {
                  status: {
                    type: "string",
                    enum: [
                      "none",
                      "pending",
                      "completed",
                      "aggregate_unresolved",
                    ],
                  },
                  amountRaw: rawAmount,
                  wireId: rawAmount,
                  evidence: { type: "array", items: evidenceRef },
                },
              },
              localNetworkFees: {
                type: "array",
                items: {
                  type: "object",
                  required: [
                    "transaction",
                    "amountRaw",
                    "includedInOwnerFeeMovements",
                  ],
                  properties: {
                    transaction: evidenceRef,
                    amountRaw: { type: ["string", "null"] },
                    includedInOwnerFeeMovements: { type: "boolean" },
                  },
                },
              },
            },
          },
          t3: {
            type: "object",
            required: [
              "hub",
              "root",
              "owner",
              "recipient",
              "queryId",
              "amountRaw",
              "stage",
              "reserveRoots",
              "basketRaw",
              "deliveredRaw",
              "feeBreakdown",
              "localNetworkFees",
            ],
            description:
              "T3 mint/root-delivery or completed redemption into a controller-owned receiver. Gross mint debits split principal and verified fee; redemption feeAmountsRaw are withheld before delivery, never an additional debit. Missing exact archive state keeps feeBreakdown unavailable. Receipts or total-supply changes alone do not confirm settlement.",
            properties: {
              hub: { type: "string" },
              root: { type: "string" },
              owner: { type: "string" },
              recipient: { type: "string" },
              queryId: rawAmount,
              amountRaw: { type: ["string", "null"] },
              mintedRaw: rawAmount,
              stage: {
                type: "string",
                enum: ["minted", "redeemed", "unresolved"],
              },
              rootQueryId: rawAmount,
              wireId: rawAmount,
              requestHash: { type: "string" },
              payoutId: rawAmount,
              receiver: { type: "string" },
              reserveRoots: {
                type: "array",
                minItems: 3,
                maxItems: 3,
                items: { type: "string" },
              },
              basketRaw: {
                type: "array",
                minItems: 3,
                maxItems: 3,
                items: rawAmount,
              },
              deliveredRaw: {
                type: "array",
                minItems: 3,
                maxItems: 3,
                items: rawAmount,
              },
              feeBreakdown: {
                type: "string",
                enum: ["verified", "unavailable"],
              },
              feeAmountsRaw: {
                type: "array",
                minItems: 3,
                maxItems: 3,
                items: rawAmount,
              },
              feeEvidence: {
                type: "object",
                required: [
                  "kind",
                  "stateBeforeHash",
                  "stateAfterHash",
                  "beforeSeqno",
                  "afterSeqno",
                  "transactions",
                ],
                properties: {
                  kind: { type: "string", enum: ["t3_mint", "t3_burn"] },
                  stateBeforeHash: { type: "string" },
                  stateAfterHash: { type: "string" },
                  beforeSeqno: { type: "integer" },
                  afterSeqno: { type: "integer" },
                  transactions: { type: "array", items: evidenceRef },
                },
              },
              burnRecovery: {
                $ref: "#/components/schemas/LedgerT3BurnRecovery",
              },
              identityEvidence: {
                type: "object",
                required: ["account", "method", "args", "result", "observedAt"],
                properties: {
                  account: { type: "string" },
                  method: { type: "string", enum: ["redemption_identity"] },
                  args: {
                    type: "array",
                    minItems: 2,
                    maxItems: 2,
                    items: { type: "string" },
                  },
                  result: {
                    type: "array",
                    minItems: 4,
                    maxItems: 4,
                    items: rawAmount,
                  },
                  observedAt: { type: "string", format: "date-time" },
                },
              },
              localNetworkFees: {
                type: "array",
                items: {
                  type: "object",
                  required: [
                    "transaction",
                    "amountRaw",
                    "includedInOwnerFeeMovements",
                  ],
                  properties: {
                    transaction: evidenceRef,
                    amountRaw: { type: ["string", "null"] },
                    includedInOwnerFeeMovements: { type: "boolean" },
                  },
                },
              },
            },
          },
          bridge: {
            type: "object",
            required: [
              "messageId",
              "nonce",
              "amountRaw",
              "sourceDomain",
              "destinationDomain",
              "soraAssetId",
              "recipient32",
              "tonMaster",
              "tonWallet",
              "tonOwner",
              "masterCodeHash",
              "localStage",
              "counterpartyStatus",
              "localNetworkFees",
            ],
            description:
              "SCCP linkage and TON-local stage only. Confirmed settlement never implies a remote receipt, source ownership, matching counterparty balance, or available reverse bridge route.",
            properties: {
              messageId: { type: ["string", "null"] },
              nonce: { type: ["string", "null"] },
              amountRaw: rawAmount,
              sourceDomain: { type: "integer", minimum: 0, maximum: 5 },
              destinationDomain: { type: "integer", minimum: 0, maximum: 5 },
              soraAssetId: { type: ["string", "null"] },
              recipient32: { type: "string" },
              tonMaster: { type: "string" },
              tonWallet: { type: "string" },
              tonOwner: { type: "string" },
              masterCodeHash: { type: ["string", "null"] },
              verifier: { type: "string" },
              verifierCodeHash: { type: "string" },
              localStage: {
                type: "string",
                enum: ["burned", "minted", "unresolved"],
              },
              counterpartyStatus: { type: "string", enum: ["unverified"] },
              localNetworkFees: {
                type: "array",
                description:
                  "Observed transaction fees, not additive charges. Owned fees are already movement entries; nonowned fees do not imply a separate recipient debit.",
                items: {
                  type: "object",
                  required: [
                    "transaction",
                    "amountRaw",
                    "includedInOwnerFeeMovements",
                  ],
                  properties: {
                    transaction: evidenceRef,
                    amountRaw: { type: ["string", "null"] },
                    includedInOwnerFeeMovements: { type: "boolean" },
                  },
                },
              },
            },
          },
          pool: { type: "string" },
          factory: { type: "string" },
          series: { type: "string" },
          seriesId: rawAmount,
          positionId: rawAmount,
          wireId: rawAmount,
          positionHash: { type: "string", pattern: "^[0-9a-f]{64}$" },
          notionalRaw: rawAmount,
          premiumRaw: rawAmount,
          collateralRaw: rawAmount,
          protocolFeeRaw: rawAmount,
          queryId: rawAmount,
          evidence: { type: "array", items: evidenceRef },
        },
      },
    },
  },
  LedgerPage: {
    type: "object",
    required: ["network", "account", "events", "nextCursor", "coverage"],
    properties: {
      network: { type: "string" },
      account: { type: "string" },
      events: {
        type: "array",
        items: { $ref: "#/components/schemas/LedgerEvent" },
      },
      nextCursor: { type: ["string", "null"] },
      coverage: {
        type: "object",
        required: [
          "generation",
          "publishedAt",
          "headObservedAt",
          "checkedAt",
          "snapshotComplete",
          "historyComplete",
          "decodingComplete",
          "syncing",
          "oldestUtime",
          "newestUtime",
          "syncedAt",
          "issues",
        ],
        properties: {
          generation: { type: ["string", "null"], format: "uuid" },
          publishedAt: nullableDate,
          headObservedAt: nullableDate,
          checkedAt: {
            ...nullableDate,
            description:
              "Conservative observation time of the latest full dependency verification of this generation. Root polling consumers pin this with generation; publication time is never a chain watermark.",
          },
          snapshotComplete: {
            type: "boolean",
            description:
              "Published immutable snapshot. Unpublished runs expose no event pages.",
          },
          historyComplete: {
            type: "boolean",
            description:
              "Observed owner and discovered related account chains link to genesis. Discovery is limited to configured roots and observed wallets; this is not portfolio or tax completeness.",
          },
          decodingComplete: { type: "boolean" },
          syncing: { type: "boolean" },
          oldestUtime: { type: ["integer", "null"] },
          newestUtime: { type: ["integer", "null"] },
          syncedAt: {
            ...nullableDate,
            description: "Generation publication time, equal to publishedAt.",
          },
          issues: { type: "array", items: { type: "string" } },
          discoveryScope: {
            type: "string",
            enum: ["configured_roots_and_observed_wallets"],
          },
          relatedAccounts: {
            type: "array",
            items: {
              type: "object",
              required: ["account", "generation", "historyComplete", "role"],
              properties: {
                account: { type: "string" },
                generation: { type: ["string", "null"] },
                historyComplete: { type: "boolean" },
                role: {
                  type: "string",
                  enum: [
                    "owner",
                    "owned_jetton_wallet",
                    "controlled_contract",
                    "counterparty",
                    "pool",
                  ],
                },
              },
            },
          },
        },
      },
    },
  },
};
export const ledgerPaths = {
  "/api/indexer/v1/accounts/{addr}/ledger": {
    get: {
      summary:
        "Durable owner ledger with exact settlement evidence and explicit coverage",
      description:
        "Schedules independent PostgreSQL backfill. Poll while syncing; unpublished snapshots have no events. Atomic amounts are strings. Cursor generations are fixed and retain their date bounds. No fiat valuation or tax classification is implied.",
      parameters: [
        { $ref: "#/components/parameters/addr" },
        {
          name: "from_utime",
          in: "query",
          description: "Inclusive UTC Unix seconds",
          schema: { type: "integer", minimum: 0 },
        },
        {
          name: "to_utime",
          in: "query",
          description: "Exclusive UTC Unix seconds",
          schema: { type: "integer", minimum: 0 },
        },
        {
          name: "limit",
          in: "query",
          schema: { type: "integer", minimum: 1, maximum: 500, default: 100 },
        },
        {
          name: "cursor",
          in: "query",
          schema: { type: "string", maxLength: 2048 },
        },
      ],
      responses: {
        200: {
          description: "Ledger snapshot and coverage",
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/LedgerPage" },
            },
          },
        },
        400: { description: "Invalid account, date bounds, or cursor" },
        503: { description: "PostgreSQL ledger not configured or unavailable" },
      },
    },
  },
};
