export const buildDocsHtml = () => {
  const parts = [
    '<!doctype html>',
    '<html>',
    '  <head>',
    '    <meta charset=\"utf-8\" />',
    '    <title>TONSWAP Indexer API</title>',
    '    <style>',
    '      body { font-family: ui-sans-serif, system-ui, -apple-system; padding: 20px; line-height: 1.4; }',
    '      .row { margin-bottom: 10px; }',
    '      textarea { width: 100%; height: 120px; }',
    '      pre { background: #f6f6f6; padding: 12px; overflow: auto; }',
    '      input, select, button { padding: 6px; }',
    '    </style>',
    '  </head>',
    '  <body>',
    '    <h1>TONSWAP Indexer API</h1>',
    '    <p><a href=\"/api/indexer/v1/openapi.json\">OpenAPI JSON</a></p>',
    '    <div class=\"row\">',
    '      <label>Endpoint:</label>',
    '      <select id=\"endpoint\">',
    '        <option value=\"/api/indexer/v1/health\">/health</option>',
    '        <option value=\"/api/indexer/v1/metrics\">/metrics</option>',
    '        <option value=\"/api/indexer/v1/metrics/prometheus\">/metrics/prometheus</option>',
    '        <option value=\"/api/indexer/v1/accounts/{addr}/balance\">/accounts/{addr}/balance</option>',
    '        <option value=\"/api/indexer/v1/accounts/{addr}/balances\">/accounts/{addr}/balances</option>',
    '        <option value=\"/api/indexer/v1/accounts/{addr}/assets\">/accounts/{addr}/assets</option>',
    '        <option value=\"/api/indexer/v1/accounts/{addr}/txs\">/accounts/{addr}/txs</option>',
    '        <option value=\"/api/indexer/v1/accounts/{addr}/state\">/accounts/{addr}/state</option>',
    '        <option value=\"/api/indexer/v1/debug\">/debug</option>',
    '      </select>',
    '    </div>',
    '    <div class=\"row\">',
    '      <label>Address:</label>',
    '      <input id=\"addr\" placeholder=\"EQ... or 0:...\" size=\"60\" />',
    '    </div>',
    '    <div class=\"row\">',
    '      <label>Query string:</label>',
    '      <input id=\"query\" placeholder=\"page=1\" size=\"40\" />',
    '    </div>',
    '    <div class=\"row\">',
    '      <label>Bearer token (admin):</label>',
    '      <input id=\"token\" placeholder=\"optional\" size=\"60\" />',
    '    </div>',
    '    <div class=\"row\">',
    '      <button id=\"run\">Send</button>',
    '    </div>',
    '    <pre id=\"output\"></pre>',
    '',
    '    <script>',
    '      const output = document.getElementById(\"output\");',
    '      const endpoint = document.getElementById(\"endpoint\");',
    '      const addr = document.getElementById(\"addr\");',
    '      const query = document.getElementById(\"query\");',
    '      const token = document.getElementById(\"token\");',
    '      const run = document.getElementById(\"run\");',
    '',
    '      const buildUrl = () => {',
    '        let path = endpoint.value;',
    '        if (path.includes(\"{addr}\")) {',
    '          path = path.replace(\"{addr}\", encodeURIComponent(addr.value || \"\"));',
    '        }',
    '        const qs = query.value ? `?${query.value}` : \"\";',
    '        return path + qs;',
    '      };',
    '',
    '      run.addEventListener(\"click\", async () => {',
    '        output.textContent = \"Loading...\";',
    '        const url = buildUrl();',
    '        const headers = {};',
    '        if (token.value) headers[\"Authorization\"] = `Bearer ${token.value}`;',
    '        try {',
    '          const res = await fetch(url, { headers });',
    '          const text = await res.text();',
    '          try {',
    '            output.textContent = JSON.stringify(JSON.parse(text), null, 2);',
    '          } catch {',
    '            output.textContent = text;',
    '          }',
    '        } catch (err) {',
    '          output.textContent = String(err);',
    '        }',
    '      });',
    '    </script>',
    '  </body>',
    '</html>',
  ];

  return parts.join('\\n');
};
